model_type: "yolov8"

roboflow_project_rbf: "small-leaf-detection"
roboflow_version_rbf: 1

roboflow_project_nas: "leaf-count-w5m5l"
roboflow_version_nas: 1

yolov8_model_path: "/home/juliocesar/leaf-detection/checkpoints/yolov10/large/train4/best.pt"


yolonas_arch: "yolo_nas_l"
data_num_classes: 1
data_classes: ["leaf"]
yolonas_model_path: "/home/juliocesar/leaf-detection/checkpoints/yolonas/large/train5/ckpt_best.pth"

detect_parameters:
  confidence: 50.0
  overlap: 50.0

  use_slice: True
  slice_wh: [640,640]
  slice_overlap_ratio: [0.3, 0.3]
  slice_iou_threshold: 0.2
  slice_fill: False


sam2_ckpt_path: "/home/juliocesar/leaf-detection/checkpoints/sam2/sam2_hiera_tiny.pt"
sam2_cfg: "sam2_hiera_t.yaml"


