model_type: "yolonas"

roboflow_project_rbf: "small-leaf-detection"
roboflow_version_rbf: 1

roboflow_project_nas: "leaf-count-w5m5l"
roboflow_version_nas: 1

yolov8_custom_model: "./pretrained_models/yolov8/train2/best.pt"


yolonas_arch: "yolo_nas_l"
data_num_classes: 1
yolonas_model_path: "./pretrained_models/yolonas/train1/ckpt_best.pth"

detect_parameters:
  confidence: 50.0
  overlap: 50.0
  slice_detect: true
  slice_w: 640
  slice_h: 640
  slice_overlap_ratio_w: 0.1
  slice_overlap_ratio_h: 0.1


use_spec_detect_parameters: false
spec_detect_parameters:
  img10:
    confidence: 50.0
    overlap: 50.0
    slice_detect: true
    slice_w: 480
    slice_h: 480
    slice_overlap_ratio_w: 0.1
    slice_overlap_ratio_h: 0.1

  img11:
    confidence: 50.0
    overlap: 50.0
    slice_detect: true
    slice_w: 480
    slice_h: 480
    slice_overlap_ratio_w: 0.1
    slice_overlap_ratio_h: 0.1
